/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        hometab = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jphome = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMovie = new javax.swing.JTextField();
        txtCompany = new javax.swing.JTextField();
        txtDirector = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddHome = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDeleteHome = new javax.swing.JButton();
        jp2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comAddress = new javax.swing.JTextField();
        comCompany = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        btnAddCompany = new javax.swing.JButton();
        btnUpdateCompany = new javax.swing.JButton();
        btnDeleteCompany = new javax.swing.JButton();
        jp4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        quoQuote = new javax.swing.JTextField();
        quoAuthor = new javax.swing.JTextField();
        quoSaid = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        quoButton = new javax.swing.JButton();
        btnQuoteUpdate = new javax.swing.JButton();
        btnDeleteQuote = new javax.swing.JButton();
        jp5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        diName = new javax.swing.JTextField();
        diBirthdate = new javax.swing.JTextField();
        diNumDirected = new javax.swing.JTextField();
        diNumActor = new javax.swing.JTextField();
        direcButton = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        btnDirectorUpdate = new javax.swing.JButton();
        btnDeleteDirector = new javax.swing.JButton();
        jp1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        movMovie = new javax.swing.JTextField();
        movYear = new javax.swing.JTextField();
        movGenre = new javax.swing.JTextField();
        movLength = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        movButton = new javax.swing.JButton();
        btnMovUpdate = new javax.swing.JButton();
        btnDeleteMovie = new javax.swing.JButton();
        jp3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        actName1 = new javax.swing.JTextField();
        actBirth1 = new javax.swing.JTextField();
        actMany1 = new javax.swing.JTextField();
        actAppear1 = new javax.swing.JTextField();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        actButton1 = new javax.swing.JButton();
        btnActorUpdate = new javax.swing.JButton();
        btnDeleteActor1 = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel17.setText("jLabel17");

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 128));

        tab1.setBackground(new java.awt.Color(204, 204, 255));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Movie");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tab2.setBackground(new java.awt.Color(204, 204, 255));
        tab2.setForeground(new java.awt.Color(204, 204, 255));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Company");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel2)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tab3.setBackground(new java.awt.Color(204, 204, 255));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Actor");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tab4.setBackground(new java.awt.Color(204, 204, 255));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Quote");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tab5.setBackground(new java.awt.Color(204, 204, 255));
        tab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Director");

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel5)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Movie Industry");

        hometab.setBackground(new java.awt.Color(204, 204, 255));
        hometab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hometabMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Home");

        javax.swing.GroupLayout hometabLayout = new javax.swing.GroupLayout(hometab);
        hometab.setLayout(hometabLayout);
        hometabLayout.setHorizontalGroup(
            hometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hometabLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hometabLayout.setVerticalGroup(
            hometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tab5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hometab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(hometab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jphome.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setText("Company");

        jLabel8.setText("Movie");

        jLabel9.setText("Director");

        txtMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovieActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Movie", "Company", "Director"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnAddHome.setText("Add");
        btnAddHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHomeActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDeleteHome.setText("Delete");
        btnDeleteHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jphomeLayout = new javax.swing.GroupLayout(jphome);
        jphome.setLayout(jphomeLayout);
        jphomeLayout.setHorizontalGroup(
            jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jphomeLayout.createSequentialGroup()
                .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jphomeLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(22, 22, 22)
                        .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDirector, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(txtCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(txtMovie)))
                    .addGroup(jphomeLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jphomeLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnAddHome)
                                .addGap(26, 26, 26)
                                .addComponent(btnUpdate)
                                .addGap(28, 28, 28)
                                .addComponent(btnDeleteHome)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jphomeLayout.setVerticalGroup(
            jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jphomeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jphomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddHome)
                    .addComponent(btnUpdate)
                    .addComponent(btnDeleteHome))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jp2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel11.setText("Name of Company");

        jLabel12.setText("Address");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Company", "Address"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        btnAddCompany.setText("Add");
        btnAddCompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCompanyMouseClicked(evt);
            }
        });
        btnAddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCompanyActionPerformed(evt);
            }
        });

        btnUpdateCompany.setText("Update");
        btnUpdateCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCompanyActionPerformed(evt);
            }
        });

        btnDeleteCompany.setText("Delete");
        btnDeleteCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCompanyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnAddCompany)
                                .addGap(33, 33, 33)
                                .addComponent(btnUpdateCompany)
                                .addGap(35, 35, 35)
                                .addComponent(btnDeleteCompany)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(comAddress))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(comAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteCompany)
                    .addComponent(btnUpdateCompany)
                    .addComponent(btnAddCompany))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jp4.setBackground(new java.awt.Color(204, 204, 255));
        jp4.setPreferredSize(new java.awt.Dimension(479, 414));

        jLabel22.setText("Quote");

        jLabel23.setText("Author");

        jLabel24.setText("Movies this quote is said");

        quoQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quoQuoteActionPerformed(evt);
            }
        });

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Quote", "Author", "Movies this quote said"
            }
        ));
        jTable9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable9MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTable9);

        quoButton.setText("Add");
        quoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quoButtonMouseClicked(evt);
            }
        });

        btnQuoteUpdate.setText("Update");
        btnQuoteUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuoteUpdateActionPerformed(evt);
            }
        });

        btnDeleteQuote.setText("Delete");
        btnDeleteQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteQuoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(quoButton)
                        .addGap(35, 35, 35)
                        .addComponent(btnQuoteUpdate)
                        .addGap(38, 38, 38)
                        .addComponent(btnDeleteQuote))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(29, 29, 29)
                        .addComponent(quoSaid))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quoQuote, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(quoAuthor))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(quoQuote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(quoAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(quoSaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quoButton)
                    .addComponent(btnQuoteUpdate)
                    .addComponent(btnDeleteQuote))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jp5.setBackground(new java.awt.Color(204, 204, 255));
        jp5.setPreferredSize(new java.awt.Dimension(479, 414));

        jLabel25.setText("Name");

        jLabel26.setText("Birthdate");

        jLabel27.setText("Number of movies directed");

        jLabel28.setText("Number of movies he/she is an actor");

        direcButton.setText("Add");
        direcButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                direcButtonMouseClicked(evt);
            }
        });

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Birthdate", "Number of movies directed", "Number of movies he/she is an actor"
            }
        ));
        jTable10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable10MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jTable10);

        btnDirectorUpdate.setText("Update");
        btnDirectorUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectorUpdateActionPerformed(evt);
            }
        });

        btnDeleteDirector.setText("Delete");
        btnDeleteDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDirectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp5Layout = new javax.swing.GroupLayout(jp5);
        jp5.setLayout(jp5Layout);
        jp5Layout.setHorizontalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(direcButton)
                        .addGap(42, 42, 42)
                        .addComponent(btnDirectorUpdate)
                        .addGap(45, 45, 45)
                        .addComponent(btnDeleteDirector))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28))
                        .addGap(27, 27, 27)
                        .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(diNumActor, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(diNumDirected)
                            .addComponent(diBirthdate)
                            .addComponent(diName))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jp5Layout.setVerticalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(diName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(diBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(diNumDirected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(diNumActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteDirector)
                    .addComponent(btnDirectorUpdate)
                    .addComponent(direcButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jp1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel13.setText("Movie");

        jLabel14.setText("Year of Release");

        jLabel15.setText("Genre");

        jLabel16.setText("Length in Minutes");

        movYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movYearActionPerformed(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Movie", "Year of Release", "Genre", "Length in Minutes"
            }
        ));
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        movButton.setText("Add");
        movButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movButtonMouseClicked(evt);
            }
        });

        btnMovUpdate.setText("Update");
        btnMovUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovUpdateActionPerformed(evt);
            }
        });

        btnDeleteMovie.setText("Delete");
        btnDeleteMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMovieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(31, 31, 31)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(movYear, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(movMovie)
                            .addComponent(movGenre)
                            .addComponent(movLength)))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(movButton)
                        .addGap(39, 39, 39)
                        .addComponent(btnMovUpdate)
                        .addGap(45, 45, 45)
                        .addComponent(btnDeleteMovie)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(movYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(movGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(movLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movButton)
                    .addComponent(btnMovUpdate)
                    .addComponent(btnDeleteMovie))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jp3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel29.setText("Name");

        jLabel30.setText("Type what movies this actor appear");

        jLabel31.setText("Date of Birth");

        jLabel32.setText("How many movies this actor appear?");

        actName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actName1ActionPerformed(evt);
            }
        });

        actMany1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actMany1ActionPerformed(evt);
            }
        });

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Birthdate", "No. of movies appear", "ovies"
            }
        ));
        jTable11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable11MouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(jTable11);

        actButton1.setText("Add");
        actButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actButton1MouseClicked(evt);
            }
        });
        actButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actButton1ActionPerformed(evt);
            }
        });

        btnActorUpdate.setText("Update");
        btnActorUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActorUpdateActionPerformed(evt);
            }
        });

        btnDeleteActor1.setText("Delete");
        btnDeleteActor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp3Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(actMany1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp3Layout.createSequentialGroup()
                                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp3Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(actButton1)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnActorUpdate))
                                    .addComponent(jLabel30))
                                .addGap(22, 22, 22)
                                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(actAppear1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDeleteActor1))))
                        .addGroup(jp3Layout.createSequentialGroup()
                            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel29)
                                .addComponent(jLabel31))
                            .addGap(133, 133, 133)
                            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(actName1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addComponent(actBirth1))))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actBirth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(actMany1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(actAppear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActorUpdate)
                            .addComponent(actButton1)
                            .addComponent(btnDeleteActor1))
                        .addGap(36, 36, 36)))
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jphome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 410, Short.MAX_VALUE)
                    .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 408, Short.MAX_VALUE)
                    .addComponent(jp4, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 410, Short.MAX_VALUE)
                    .addComponent(jp5, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 408, Short.MAX_VALUE)
                    .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 408, Short.MAX_VALUE)
                    .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jphome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp5, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int id = 0;
    private void btnAddHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHomeActionPerformed
        // TODO add your handling code here:
        //code to load data into table 
        //validation for not leave blank data
        
        if (txtMovie.getText().equals("") || txtCompany.getText().equals("") || txtDirector.getText().equals("")) {
            //if any of three field left blank then left message
            JOptionPane.showMessageDialog(this, "Please enter all Data");
        } else {
            
            id++;
            int ID = id;
            // if all data field
            // store enter data into String array --data---
            String data[] = {Integer.toString(ID), txtMovie.getText(), txtCompany.getText(), txtDirector.getText()};

            DefaultTableModel tblHome = (DefaultTableModel) jTable1.getModel();
            //add string array data
            tblHome.addRow(data); //row added

            //successfully added message
            JOptionPane.showMessageDialog(this, "Add Data Successfully");
            //clear textfield for new entry
            txtMovie.setText("");
            txtCompany.setText("");
            txtDirector.setText("");
        }
    }//GEN-LAST:event_btnAddHomeActionPerformed

    private void txtMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovieActionPerformed

    private void tab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab5MouseClicked
        // TODO add your handling code here:
        jp5.setVisible(true);
        jp2.setVisible(false);
        jphome.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        tab5.setBackground(Color.white);
        hometab.setBackground(new Color(204, 204, 255));
        tab1.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(204, 204, 255));
        tab3.setBackground(new Color(204, 204, 255));
        tab4.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_tab5MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        // TODO add your handling code here:
        jp4.setVisible(true);
        jp2.setVisible(false);
        jphome.setVisible(false);
        jp3.setVisible(false);
        jp5.setVisible(false);
        tab4.setBackground(Color.white);
        hometab.setBackground(new Color(204, 204, 255));
        tab1.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(204, 204, 255));
        tab3.setBackground(new Color(204, 204, 255));
        tab5.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_tab4MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        // TODO add your handling code here:
        jp3.setVisible(true);
        jp2.setVisible(false);
        jphome.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        tab3.setBackground(Color.white);
        hometab.setBackground(new Color(204, 204, 255));
        tab1.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(204, 204, 255));
        tab4.setBackground(new Color(204, 204, 255));
        tab5.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_tab3MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        // TODO add your handling code here:

        jp2.setVisible(true);
        jp1.setVisible(false);
        jphome.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        tab2.setBackground(Color.white);
        hometab.setBackground(new Color(204, 204, 255));
        tab1.setBackground(new Color(204, 204, 255));
        tab3.setBackground(new Color(204, 204, 255));
        tab4.setBackground(new Color(204, 204, 255));
        tab5.setBackground(new Color(204, 204, 255));

    }//GEN-LAST:event_tab2MouseClicked

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        // TODO add your handling code here:
        jp1.setVisible(true);
        jphome.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        tab1.setBackground(Color.white);
        hometab.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(204, 204, 255));
        tab3.setBackground(new Color(204, 204, 255));
        tab4.setBackground(new Color(204, 204, 255));
        tab5.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_tab1MouseClicked

    private void hometabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hometabMouseClicked
        // TODO add your handling code here:
        jphome.setVisible(true);
        jp2.setVisible(false);

        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        jp1.setVisible(false);
        hometab.setBackground(Color.white);
        tab2.setBackground(new Color(204, 204, 255));
        tab1.setBackground(new Color(204, 204, 255));
        tab3.setBackground(new Color(204, 204, 255));
        tab4.setBackground(new Color(204, 204, 255));
        tab5.setBackground(new Color(204, 204, 255));
    }//GEN-LAST:event_hometabMouseClicked

    private void btnAddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCompanyActionPerformed
        private int idCom=0;
    private void btnAddCompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCompanyMouseClicked
        // TODO add your handling code here:
        //code to load data into table 
        //validation for not leave blank data
        
        if (comCompany.getText().equals("") || comAddress.getText().equals("")) {
            //if any of three field left blank then left message
            JOptionPane.showMessageDialog(this, "Please enter all Data");
        } else {
            
            idCom++;
            int ID = idCom;
            // if all data field
            // store enter data into String array --data---
            String companyData[] = {Integer.toString(ID), comCompany.getText(), comAddress.getText()};

            DefaultTableModel tblCompany = (DefaultTableModel) jTable4.getModel();
            //add string array data
            tblCompany.addRow(companyData); //row added

            //successfully added message
            JOptionPane.showMessageDialog(this, "Add Data Successfully");
            //clear textfield for new entry
            comCompany.setText("");
            comAddress.setText("");

        }
    }//GEN-LAST:event_btnAddCompanyMouseClicked
    private int idMov=0;
    private void movButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movButtonMouseClicked
        // TODO add your handling code here:
        //code to load data into table 
        //validation for not leave blank data
        
        if (movMovie.getText().equals("") || movYear.getText().equals("") || movGenre.getText().equals("")
                || movLength.getText().equals("")) {
            //if any of three field left blank then left message
            JOptionPane.showMessageDialog(this, "Please enter all Data");
        } else {
            
            idMov++;
            int ID = idMov;
            // if all data field
            // store enter data into String array --data---
            String movieData[] = {Integer.toString(ID), movMovie.getText(), movYear.getText(),
                 movGenre.getText(), movLength.getText()};

            DefaultTableModel tblMovie = (DefaultTableModel) jTable5.getModel();
            //add string array data
            tblMovie.addRow(movieData); //row added

            //successfully added message
            JOptionPane.showMessageDialog(this, "Add Data Successfully");
            //clear textfield for new entry
            movMovie.setText("");
            movYear.setText("");
            movGenre.setText("");
            movLength.setText("");

        }
    }//GEN-LAST:event_movButtonMouseClicked

    private void quoQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quoQuoteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_quoQuoteActionPerformed
    private int idQuo=0;
    private void quoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quoButtonMouseClicked
        // TODO add your handling code here:
        
        if (quoQuote.getText().equals("") || quoAuthor.getText().equals("") || quoSaid.getText().equals("")) {
            //if any of three field left blank then left message
            JOptionPane.showMessageDialog(this, "Please enter all Data");
        } else {
            idQuo++;
            int ID = idQuo;
            
            // if all data field
            // store enter data into String array --data---
            String quoteData[] = {Integer.toString(ID), quoQuote.getText(), quoAuthor.getText(),
                 quoSaid.getText()};

            DefaultTableModel tblQuote = (DefaultTableModel) jTable9.getModel();
            //add string array data
            tblQuote.addRow(quoteData); //row added

            //successfully added message
            JOptionPane.showMessageDialog(this, "Add Data Successfully");
            //clear textfield for new entry
            quoQuote.setText("");
            quoAuthor.setText("");
            quoSaid.setText("");


    }//GEN-LAST:event_quoButtonMouseClicked

    }


    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        //set data to their corresponding textfield

        DefaultTableModel tblCompany = (DefaultTableModel) jTable4.getModel();

        //set data to text field when raw is selected
        String tblcom = tblCompany.getValueAt(jTable4.getSelectedRow(), 1).toString();
        String tblAddress = tblCompany.getValueAt(jTable4.getSelectedRow(), 2).toString();

        //set to textfield
        comCompany.setText(tblcom);
        comAddress.setText(tblAddress);

    }//GEN-LAST:event_jTable4MouseClicked

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
        //set data to their corresponding textfield

        DefaultTableModel tblMovie = (DefaultTableModel) jTable5.getModel();

        //set data to text field when raw is selected
        String tblmovMovie = tblMovie.getValueAt(jTable5.getSelectedRow(), 1).toString();
        String tblmovYear = tblMovie.getValueAt(jTable5.getSelectedRow(), 2).toString();
        String tblmovGenre = tblMovie.getValueAt(jTable5.getSelectedRow(), 3).toString();
        String tblmovLength = tblMovie.getValueAt(jTable5.getSelectedRow(), 4).toString();

        //set to textfield
        movMovie.setText(tblmovMovie);
        movYear.setText(tblmovYear);
        movGenre.setText(tblmovGenre);
        movLength.setText(tblmovLength);


    }//GEN-LAST:event_jTable5MouseClicked

    private void btnMovUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblMovie = (DefaultTableModel) jTable5.getModel();
        if (jTable5.getSelectedRowCount() == 1) {
            //if single row is selected then update

            String movieMovie = movMovie.getText();
            String year = movYear.getText();
            String genre = movGenre.getText();
            String length = movLength.getText();

            //set updated value on table row
            tblMovie.setValueAt(movieMovie, jTable5.getSelectedRow(), 1);
            tblMovie.setValueAt(year, jTable5.getSelectedRow(), 2);
            tblMovie.setValueAt(genre, jTable5.getSelectedRow(), 3);
            tblMovie.setValueAt(length, jTable5.getSelectedRow(), 4);

            //update message display
            JOptionPane.showMessageDialog(this, "Updated Successfully..");
            
            movMovie.setText("");
            movYear.setText("");
            movGenre.setText("");
            movLength.setText("");

        } else {
            if (jTable5.getRowCount() == 0) {

                //if table is empty
                JOptionPane.showMessageDialog(this, "Table is Empty..");
            } else {

                //if no row is selected or multiple row is selected
                JOptionPane.showMessageDialog(this, "Select single row to be updated..");
            }

        }
    }//GEN-LAST:event_btnMovUpdateActionPerformed

    private void jTable9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable9MouseClicked
        // TODO add your handling code here:
        //set data to their corresponding textfield

        DefaultTableModel tblQuote = (DefaultTableModel) jTable9.getModel();

        //set data to text field when raw is selected
        String tblquoQuote = tblQuote.getValueAt(jTable9.getSelectedRow(), 1).toString();
        String tblquoAuthor = tblQuote.getValueAt(jTable9.getSelectedRow(), 2).toString();
        String tblquoSaid = tblQuote.getValueAt(jTable9.getSelectedRow(), 3).toString();

        //set to textfield
        quoQuote.setText(tblquoQuote);
        quoAuthor.setText(tblquoAuthor);
        quoSaid.setText(tblquoSaid);

    }//GEN-LAST:event_jTable9MouseClicked

    private void btnQuoteUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuoteUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblQuote = (DefaultTableModel) jTable9.getModel();
        if (jTable9.getSelectedRowCount() == 1) {
            //if single row is selected then update

            String quoteQuo = quoQuote.getText();
            String authorQuo = quoAuthor.getText();
            String saIdQuo = quoSaid.getText();

            //set updated value on table row
            tblQuote.setValueAt(quoteQuo, jTable9.getSelectedRow(), 1);
            tblQuote.setValueAt(authorQuo, jTable9.getSelectedRow(), 2);
            tblQuote.setValueAt(saIdQuo, jTable9.getSelectedRow(), 3);

            //update message display
            JOptionPane.showMessageDialog(this, "Updated Successfully..");
            
            quoQuote.setText("");
            quoAuthor.setText("");
            quoSaid.setText("");

        } else {
            if (jTable9.getRowCount() == 0) {

                //if table is empty
                JOptionPane.showMessageDialog(this, "Table is Empty..");
            } else {

                //if no row is selected or multiple row is selected
                JOptionPane.showMessageDialog(this, "Select single row to be updated..");
            }

        }
    }//GEN-LAST:event_btnQuoteUpdateActionPerformed

    private void jTable10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable10MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblDirector = (DefaultTableModel) jTable10.getModel();

        //set data to text field when raw is selected
        String tbldiName = tblDirector.getValueAt(jTable10.getSelectedRow(), 1).toString();
        String tbldiBirthdate = tblDirector.getValueAt(jTable10.getSelectedRow(), 2).toString();
        String tbldiNumDirected = tblDirector.getValueAt(jTable10.getSelectedRow(), 3).toString();
        String tbldiNumActor = tblDirector.getValueAt(jTable10.getSelectedRow(), 4).toString();

        //set to textfield
        diName.setText(tbldiName);
        diBirthdate.setText(tbldiBirthdate);
        diNumDirected.setText(tbldiNumDirected);
        diNumActor.setText(tbldiNumActor);
    }//GEN-LAST:event_jTable10MouseClicked

    private void btnDirectorUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectorUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblDirector = (DefaultTableModel) jTable10.getModel();
        if (jTable10.getSelectedRowCount() == 1) {
            //if single row is selected then update

            String nameDi = diName.getText();
            String birthdateDi = diBirthdate.getText();
            String numDirectedDi = diNumDirected.getText();
            String numActorDi = diNumActor.getText();

            //set updated value on table row
            tblDirector.setValueAt(nameDi, jTable10.getSelectedRow(), 1);
            tblDirector.setValueAt(birthdateDi, jTable10.getSelectedRow(), 2);
            tblDirector.setValueAt(numDirectedDi, jTable10.getSelectedRow(), 3);
            tblDirector.setValueAt(numActorDi, jTable10.getSelectedRow(), 4);

            //update message display
            JOptionPane.showMessageDialog(this, "Updated Successfully..");
            
           diName.setText("");
           diBirthdate.setText("");
           diNumDirected.setText("");
           diNumActor.setText("");

        } else {
            if (jTable10.getRowCount() == 0) {

                //if table is empty
                JOptionPane.showMessageDialog(this, "Table is Empty..");
            } else {

                //if no row is selected or multiple row is selected
                JOptionPane.showMessageDialog(this, "Select single row to be updated..");
            }

        }
    }//GEN-LAST:event_btnDirectorUpdateActionPerformed

    private void btnDeleteHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHomeActionPerformed
        // TODO add your handling code here:
        //get jtable model first
        DefaultTableModel tblHome = (DefaultTableModel) jTable1.getModel();

        //delete row
        if (jTable1.getSelectedRowCount() == 1) {
            //if single row is selected then delete
            tblHome.removeRow(jTable1.getSelectedRow());

            txtMovie.setText("");
            txtCompany.setText("");
            txtDirector.setText("");

        } else {
            if (jTable1.getRowCount() == 0) {
                //if table is empty then display message
                JOptionPane.showMessageDialog(this, "Table is empty");
            } else {
                //if table is not empty but row is not selected or multiple row is selected
                JOptionPane.showMessageDialog(this, "Please select single row only for delete...");
            }
        }

    }//GEN-LAST:event_btnDeleteHomeActionPerformed

    private void btnDeleteCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCompanyActionPerformed
        // TODO add your handling code here:
        //get jtable model first
        DefaultTableModel tblCompany = (DefaultTableModel) jTable4.getModel();

        //delete row
        if (jTable4.getSelectedRowCount() == 1) {
            //if single row is selected then delete
            tblCompany.removeRow(jTable4.getSelectedRow());

            comCompany.setText("");
            comAddress.setText("");

        } else {
            if (jTable4.getRowCount() == 0) {
                //if table is empty then display message
                JOptionPane.showMessageDialog(this, "Table is empty");
            } else {
                //if table is not empty but row is not selected or multiple row is selected
                JOptionPane.showMessageDialog(this, "Please select single row only for delete...");
            }
        }
    }//GEN-LAST:event_btnDeleteCompanyActionPerformed

    private void btnDeleteMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMovieActionPerformed
        // TODO add your handling code here:
        //get jtable model first
        DefaultTableModel tblMovie = (DefaultTableModel) jTable5.getModel();

        //delete row
        if (jTable5.getSelectedRowCount() == 1) {
            //if single row is selected then delete
            tblMovie.removeRow(jTable5.getSelectedRow());

            movMovie.setText("");
            movYear.setText("");
            movGenre.setText("");
            movLength.setText("");

        } else {
            if (jTable5.getRowCount() == 0) {
                //if table is empty then display message
                JOptionPane.showMessageDialog(this, "Table is empty");
            } else {
                //if table is not empty but row is not selected or multiple row is selected
                JOptionPane.showMessageDialog(this, "Please select single row only for delete...");
            }
        }
    }//GEN-LAST:event_btnDeleteMovieActionPerformed

    private void btnDeleteQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteQuoteActionPerformed
        // TODO add your handling code here:

        //get jtable model first
        DefaultTableModel tblQuote = (DefaultTableModel) jTable9.getModel();

        //delete row
        if (jTable9.getSelectedRowCount() == 1) {
            //if single row is selected then delete
            tblQuote.removeRow(jTable9.getSelectedRow());

            quoQuote.setText("");
            quoAuthor.setText("");
            quoSaid.setText("");

        } else {
            if (jTable9.getRowCount() == 0) {
                //if table is empty then display message
                JOptionPane.showMessageDialog(this, "Table is empty");
            } else {
                //if table is not empty but row is not selected or multiple row is selected
                JOptionPane.showMessageDialog(this, "Please select single row only for delete...");
            }
        }
    }//GEN-LAST:event_btnDeleteQuoteActionPerformed

    private void btnDeleteDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDirectorActionPerformed
        // TODO add your handling code here:
        //get jtable model first
        DefaultTableModel tblDirector = (DefaultTableModel) jTable10.getModel();

        //delete row
        if (jTable10.getSelectedRowCount() == 1) {
            //if single row is selected then delete
            tblDirector.removeRow(jTable10.getSelectedRow());

            diName.setText("");
            diBirthdate.setText("");
            diNumDirected.setText("");
            diNumActor.setText("");

        } else {
            if (jTable10.getRowCount() == 0) {
                //if table is empty then display message
                JOptionPane.showMessageDialog(this, "Table is empty");
            } else {
                //if table is not empty but row is not selected or multiple row is selected
                JOptionPane.showMessageDialog(this, "Please select single row only for delete...");
            }
        }
    }//GEN-LAST:event_btnDeleteDirectorActionPerformed

    private void movYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movYearActionPerformed

    private void jTable11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable11MouseClicked

    private void actButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_actButton1MouseClicked

    private void actButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actButton1ActionPerformed

    private void btnActorUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActorUpdateActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnActorUpdateActionPerformed

    private void btnDeleteActor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActor1ActionPerformed

    private void actMany1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actMany1ActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_actMany1ActionPerformed

    private void actName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actName1ActionPerformed
    private int idDirec=0;
    private void direcButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direcButtonMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        if (diName.getText().equals("") || diBirthdate.getText().equals("") || diNumDirected.getText().equals("")
                || diNumActor.getText().equals("")) {
            //if any of three field left blank then left message
            JOptionPane.showMessageDialog(this, "Please enter all Data");
        } else {
            
            idDirec++;    
            int ID = idDirec;
            
            // if all data field
            // store enter data into String array --data---
            String directorData[] = {Integer.toString(ID), diName.getText(), diBirthdate.getText(),
                 diNumDirected.getText(), diNumActor.getText()};

            DefaultTableModel tblDirector = (DefaultTableModel) jTable10.getModel();
            //add string array data
            tblDirector.addRow(directorData); //row added

            //successfully added message
            JOptionPane.showMessageDialog(this, "Add Data Successfully");
            //clear textfield for new entry
            diName.setText("");
            diBirthdate.setText("");
            diNumDirected.setText("");
            diNumActor.setText("");
        }
    }//GEN-LAST:event_direcButtonMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblHome = (DefaultTableModel) jTable1.getModel();

        //set data to text field when raw is selected
        String tblMovie = tblHome.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String tblCompany = tblHome.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String tblDirector = tblHome.getValueAt(jTable1.getSelectedRow(), 3).toString();

        //set to textfield
        txtMovie.setText(tblMovie);
        txtCompany.setText(tblCompany);
        txtDirector.setText(tblDirector);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblDirector = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRowCount() == 1) {
            //if single row is selected then update

            String movie = txtMovie.getText();
            String company = txtCompany.getText();
            String director = txtDirector.getText();

            //set updated value on table row
            tblDirector.setValueAt(movie, jTable1.getSelectedRow(), 1);
            tblDirector.setValueAt(company, jTable1.getSelectedRow(), 2);
            tblDirector.setValueAt(director, jTable1.getSelectedRow(), 3);

            //update message display
            JOptionPane.showMessageDialog(this, "Updated Successfully..");
            
            txtMovie.setText("");
            txtCompany.setText("");
            txtDirector.setText("");

        } else {
            if (jTable1.getRowCount() == 0) {

                //if table is empty
                JOptionPane.showMessageDialog(this, "Table is Empty..");
            } else {

                //if no row is selected or multiple row is selected
                JOptionPane.showMessageDialog(this, "Select single row to be updated..");
            }

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCompanyActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblCompany = (DefaultTableModel) jTable4.getModel();
        if (jTable4.getSelectedRowCount() == 1) {
            //if single row is selected then update

            String companyCom = comCompany.getText();
            String addressCom = comAddress.getText();

            //set updated value on table row
            tblCompany.setValueAt(companyCom, jTable4.getSelectedRow(), 1);
            tblCompany.setValueAt(addressCom, jTable4.getSelectedRow(), 2);

            //update message display
            JOptionPane.showMessageDialog(this, "Updated Successfully..");
            
            comCompany.setText("");
            comAddress.setText("");

        } else {
            if (jTable4.getRowCount() == 0) {

                //if table is empty
                JOptionPane.showMessageDialog(this, "Table is Empty..");
            } else {

                //if no row is selected or multiple row is selected
                JOptionPane.showMessageDialog(this, "Select single row to be updated..");
            };

        };
    }//GEN-LAST:event_btnUpdateCompanyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actAppear1;
    private javax.swing.JTextField actBirth1;
    private javax.swing.JButton actButton1;
    private javax.swing.JTextField actMany1;
    private javax.swing.JTextField actName1;
    private javax.swing.JButton btnActorUpdate;
    private javax.swing.JButton btnAddCompany;
    private javax.swing.JButton btnAddHome;
    private javax.swing.JButton btnDeleteActor1;
    private javax.swing.JButton btnDeleteCompany;
    private javax.swing.JButton btnDeleteDirector;
    private javax.swing.JButton btnDeleteHome;
    private javax.swing.JButton btnDeleteMovie;
    private javax.swing.JButton btnDeleteQuote;
    private javax.swing.JButton btnDirectorUpdate;
    private javax.swing.JButton btnMovUpdate;
    private javax.swing.JButton btnQuoteUpdate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateCompany;
    private javax.swing.JTextField comAddress;
    private javax.swing.JTextField comCompany;
    private javax.swing.JTextField diBirthdate;
    private javax.swing.JTextField diName;
    private javax.swing.JTextField diNumActor;
    private javax.swing.JTextField diNumDirected;
    private javax.swing.JButton direcButton;
    private javax.swing.JPanel hometab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable9;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jp5;
    private javax.swing.JPanel jphome;
    private javax.swing.JButton movButton;
    private javax.swing.JTextField movGenre;
    private javax.swing.JTextField movLength;
    private javax.swing.JTextField movMovie;
    private javax.swing.JTextField movYear;
    private javax.swing.JTextField quoAuthor;
    private javax.swing.JButton quoButton;
    private javax.swing.JTextField quoQuote;
    private javax.swing.JTextField quoSaid;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtMovie;
    // End of variables declaration//GEN-END:variables
}
